apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  # vault
  OP_VAULT_INDEXER_IMAGE_NAME: production/indexer-image-name
  OP_VAULT_ENVIO_TOKEN: production/envio-token
  OP_VAULT_CHAIN_INDEXER_PG_PASSWORD: production/chain-indexer-pg-password
  OP_VAULT_CHAIN_INDEXER_PG_SUPERUSER_PASSWORD: production/chain-indexer-pg-superuser-password
  OP_VAULT_CHAIN_INDEXER_HASURA_ADMIN_SECRET: production/chain-indexer-hasura-admin-secret
  OP_VAULT_PG_BACKUP_DESTINATION: production/pg-backup-destination
  OP_VAULT_PG_BACKUP_REGION: production/pg-backup-region

  # common
  PLATFORM_NAMESPACE: platform-system
  FLUX_INTERVAL: 5m0s
  FLUX_RETRY_INTERVAL: 1m0s
  FLUX_TIMEOUT: 5m0s
  PG_INSTANCES: "3"
  PG_POOLER_INSTANCES: "3"
  PG_STORAGE: 20Gi
  PG_WAL_STORAGE: 10Gi
  PG_BACKUPS_ENABLED: "true"
  PG_BACKUP_RETENTION: 30d
  PG_BACKUP_SCHEDULE: "0 0 3 * * *"
  INDEXER_IMAGE_PULL_POLICY: Always
  INDEXER_KEEL_POLICY: force
  INDEXER_KEEL_TRIGGER: poll
  INDEXER_KEEL_POLL_INTERVAL: 1m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: common
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  timeout: 5m0s
  path: ./clusters/common
  prune: true
  wait: true
  dependsOn:
    - name: bootstrap
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 1m0s
  timeout: 5m0s
  path: ./clusters/apps
  prune: true
  wait: true
  dependsOn:
    - name: common
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: ConfigMap
        name: chain-indexer-vars
      - kind: Secret
        name: platform-secret-vars
      - kind: Secret
        name: cluster-secret-vars
