apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: ${ENVOY_REPLICAS}
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
        container:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
        pod:
          topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
              nodeTaintsPolicy: Honor
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: envoy
              matchLabelKeys:
                - gateway.envoyproxy.io/owning-gateway-name
                - gateway.envoyproxy.io/owning-gateway-namespace
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerSourceRanges: ${GATEWAY_LB_SOURCE_RANGES}
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "proxy_protocol_v2.enabled=true"
          oatlabs.oatmilk.work/external-dns: "true"
          external-dns.alpha.kubernetes.io/hostname: "*.${CLUSTER_ZONE}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      envoyPDB:
        maxUnavailable: 1
  telemetry:
    tracing:
      samplingRate: 100
      tags:
        k8s.pod.name: "%ENVIRONMENT(ENVOY_POD_NAME)%"
        k8s.namespace.name: "%ENVIRONMENT(ENVOY_POD_NAMESPACE)%"
      provider:
        type: OpenTelemetry
        backendRefs:
          - name: tempo
            namespace: tempo-system
            port: 4317
    accessLog:
      settings:
        - format:
            type: JSON
            json:
              start_time: "%START_TIME%"
              method: "%REQ(:METHOD)%"
              path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              protocol: "%PROTOCOL%"
              response_code: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%"
              duration: "%DURATION%"
              upstream_host: "%UPSTREAM_HOST%"
              upstream_cluster: "%UPSTREAM_CLUSTER%"
              authority: "%REQ(:AUTHORITY)%"
              x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
              user_agent: "%REQ(USER-AGENT)%"
              request_id: "%REQ(X-REQUEST-ID)%"
              trace_id: "%TRACE_ID%"
              bytes_received: "%BYTES_RECEIVED%"
              bytes_sent: "%BYTES_SENT%"
          sinks:
            - type: File
              file:
                path: /dev/stdout
